# Shell variables
# Generated by 'wal'
wallpaper='/home/chef/Pictures/Wallpapers/2769351.jpg'

# Special
background='#101215'
foreground='#c6cedd'
cursor='#c6cedd'

# Colors
color0='#101215'
color1='#4A5562'
color2='#596572'
color3='#3A5D8B'
color4='#4F6D98'
color5='#7589A5'
color6='#8C9DB5'
color7='#c6cedd'
color8='#8a909a'
color9='#4A5562'
color10='#596572'
color11='#3A5D8B'
color12='#4F6D98'
color13='#7589A5'
color14='#8C9DB5'
color15='#c6cedd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
